apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "metric-service-exporter.fullname" . }}-view-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "metric-service-exporter.fullname" . }}-view-metrics
subjects:
  - kind: ServiceAccount
    name: {{ template "metric-service-exporter.fullname" . }}
    namespace: {{ .Release.Namespace }}
